version: '3.3'

services:
  db:
   image: "postgres:13"
   environment:
     - POSTGRES_USER=db_user
     - POSTGRES_PASSWORD=db_password
  api:
    build: api
    command: ["./wait-for-it.sh", "db:5432", "--", "./docker-entrypoint.sh"]
    volumes:
      - storage:/storage/
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=production
      - IMAGES_STORE=/storage/
      - SQLALCHEMY_DATABASE_URI=postgresql://db_user:db_password@db:5432/
    depends_on:
     - db
  scraper:
    build: scraper
    command: ["./wait-for-it.sh", "db:5432", "--", "./docker-entrypoint.sh"]
    volumes:
      - storage:/storage/
    environment:
      - IMAGES_STORE=/storage/
      - SQLALCHEMY_DATABASE_URI=postgresql://db_user:db_password@db:5432/
    depends_on:
     - db
     - api
volumes:
  storage:
